-- 생산일자가 2022년 5월인 식품들의 식품 ID, 식품 이름, 총매출을 조회하는 SQL문
-- 총매출을 기준으로 내림차순 정렬해주시고 총매출이 같다면 식품 ID를 기준으로 오름차순 정렬
SELECT FO.PRODUCT_ID, PRODUCT_NAME, SUM(PRICE*AMOUNT) AS TOTAL_SALES FROM FOOD_PRODUCT AS FR JOIN FOOD_ORDER AS FO
ON FR.PRODUCT_ID = FO.PRODUCT_ID
WHERE FO.PRODUCE_DATE LIKE "2022-05%"
GROUP BY PRODUCT_ID
ORDER BY TOTAL_SALES DESC, FO.PRODUCT_ID ASC